{{- if and .Values.config.enabled (not .Values.config.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse-admin.fullname" . }}-config
  labels:
    {{- include "synapse-admin.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- if .Values.config.json }}
    {{- toJson .Values.config.json | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
{{- end }}
